config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'


  resources :cocktails, only: [:index, :show, :new, :create, :destroy]
  resources :doses, only: [:create, :new]
  resources :doses, only: [:destroy] # delete destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :drinks

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
  validates :name, presence: true
end

app/models/drink.rb
class Drink < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_ingredientes,
    against: [ :name, :ingredientes ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
 before_action :set_cocktail, only: [:destroy, :show]

  # GET /cocktail
  def index
    @cocktails = Cocktail.all
     if params[:query].present?
      sql_query = "name ILIKE :query OR ingredientes ILIKE :query"
      @drinks = Drink.where(sql_query, query: "%#{params[:query]}%")
    end
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new

  end

  # GET /cocktail/1/edit


  # POST /cocktail
  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'cocktail was successfully created.'
    else
      render 'new'
    end
  end

  # DELETE /cocktail/1
  def destroy
    if @cocktail.destroy
      redirect_to root_path, notice: 'cocktail was successfully destroyed.'
    else
      render @cocktail
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
    # Only allow a trusted parameter "white list" through.
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)


    # @dose.cocktail = @cocktail
    if @dose.save
      redirect_to "/cocktails"
    else
      render "doses/new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="2000">
      <img src="https://images.unsplash.com/photo-1523529364348-e930dcb39642?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="d-block w-100" alt="bar">
    </div>
    <div class="carousel-item" data-interval="3000">
      <img src="https://images.unsplash.com/photo-1481833761820-0509d3217039?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="d-block w-100" alt="relax">
    </div>
    <div class="carousel-item" data-interval="4000">
      <img src="https://images.unsplash.com/photo-1515674213736-54d14b4285b4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" class="d-block w-100" alt="taca">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="bg">
  <div class="container">
    <div class="text-primary">
      <div class="cards">
        <% if @drinks.present? %>
          <% @drinks.each do |drink| %>
            <div class="card-trip m-2">
              <%= image_tag ("cup.jpg") %>
              <div class="card-trip-infos">
                <div>
                  <h4 class="card-title block-with-text mb-2"><%= drink.name %> </h4>
                    <% a= drink.ingredientes %>
                    <% b= a.split(",") %>
                    <% b.each do |item| %>
                    <p class="card-text mr-2"><li>  <%= item %>  </li></p>
                    <% end %>
                    <h4> <strong> Modo de preparo:</strong> </h4>
                  <div class="d-flex justify-content-between" style="width: 100%">
                    <h2 class="card-trip-pricing"><%= drink.metodo %></h2>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
   <section class="drink">
    <% if @drinks.present? %>
      <% @drinks.each do |drink| %>
        <div class="col-md-12">
          <h3><%= drink.name %></h3>
          <p><%= drink.ingredientes %></p>
          <p><%= drink.metodo %></p>
        </div>
      <% end %>
    <% end %>
  </selection>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="align-items-center">
    <div class="col-sm-12 offset-md-3 col-md-6">
      <%= simple_form_for(@dose) do |f| %>
      <p class="h3 mt-2 pt-5 mb-5" style="margin-bottom: 3vh"><strong>Crie</strong> seu proprio Drink:</p>
        <%= f.error_notification %>
        <%= f.input :name %>
        <%= f.input :description, collection:["1 dose", "1/2 dose"],
                    input_html: { class: "select2" },
                    label_html: { class: 'font-weight-bolder ml-4 '},
                    label: 'Dose' %>
        <%= f.input :ingredient, collection: @ingredients,  label_html: { class: 'btn-outline-success font-weight-bolder ml-4 rounded-pill'},
                    label: 'Ingredientes', class: "btn-outline-success" %>
        <%= f.button :submit, "Adicionar" , class: "mt-3 btn btn-outline-success btn-block rounded-pill"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="flex-row-reverse navbar navbar-expand-lg navbar-lewagon fixed-top ">
  <div class="collapse navbar-collapse " id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item dropdown">
      <%= image_tag "cup.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-right " aria-labelledby="navbarDropdown">
        <%= link_to "Home" , "/cocktails", class: "fa fa-home dropdown-item btn-outline-success" %>
        <%= link_to "Criar Drink", "/doses/new", class: "dropdown-item btn-outline-success" %>
      </div>
    </li>
  </ul>
</div>
  <nav class="search">
    <form class="form-inline">
        <%= form_tag cocktails_path, method: :get do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control string required mr-sm-2",
              placeholder: "drink ou ingrediente" %>
      </a>
          <%= submit_tag "Pesquisar" ,class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
  </nav>
</div>